name: linter-check

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build
        working-directory: ./frontend
        run: |
          make install
          make build
        env:
          CI: true

      - name: Run linter
        working-directory: ./frontend
        run: make lint
      
      - name: Test & publish code coverage
        working-directory: ./frontend
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.ID_CODECLIMATE}}
        with:
          coverageCommand: npm test -- --coverage
          debug: true
